export const ActionTypes = {
    FETCH_PRODUCT: "FETCH_PRODUCT",
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    FETCH_SELECTED_PRODUCT: "FETCH_SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT"
}